import { chmod, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { spawn } from "node:child_process";
import { config, sanitiseRepoName, sanitiseVercelName } from "./config.mjs";

export async function createAndPushRepository({ workspace, job, store }) {
  await runCommand("git", ["add", "-A"], { cwd: workspace });
  await runCommand("git", ["commit", "-m", "Create website with Site Forge"], { cwd: workspace });
  const commit = (await runCommand("git", ["rev-parse", "HEAD"], { cwd: workspace })).output.trim();
  const repoName = job.requestedRepoName || await chooseRepositoryName(job.prompt, job.id);
  const endpoint = config.githubOwnerType === "org"
    ? `/orgs/${encodeURIComponent(config.githubOwner)}/repos`
    : "/user/repos";

  const repo = await githubRequest(endpoint, {
    method: "POST",
    body: {
      name: repoName,
      description: `Generated by Site Forge: ${job.prompt.slice(0, 72)}`,
      private: job.privateRepository,
      has_issues: true,
      auto_init: false,
    },
  });

  const askPassPath = join(workspace, ".site-forge-askpass.sh");
  await writeFile(
    askPassPath,
    '#!/bin/sh\ncase "$1" in\n  *Username*) echo "x-access-token" ;;\n  *Password*) echo "$GITHUB_TOKEN" ;;\nesac\n',
    "utf8",
  );
  await chmod(askPassPath, 0o700);
  try {
    await runCommand("git", ["remote", "add", "origin", repo.clone_url], { cwd: workspace });
    await runCommand("git", ["push", "-u", "origin", "main"], {
      cwd: workspace,
      env: {
        ...process.env,
        GITHUB_TOKEN: config.githubToken,
        GIT_ASKPASS: askPassPath,
        GIT_TERMINAL_PROMPT: "0",
      },
    });
  } finally {
    await rm(askPassPath, { force: true });
  }

  store.log(job, "info", `Published ${repo.full_name} at commit ${commit.slice(0, 8)}.`);
  return { repo, commit, repoName };
}

export async function deployToVercel({ repo, commit, repoName, job, store }) {
  const projectName = sanitiseVercelName(repoName);
  const project = await vercelRequest("/v11/projects", {
    method: "POST",
    body: {
      name: projectName,
      framework: "nextjs",
      gitRepository: { type: "github", repo: repo.full_name },
    },
  });

  const deployment = await vercelRequest("/v13/deployments?forceNew=1", {
    method: "POST",
    body: {
      name: projectName,
      project: project.id,
      target: "production",
      gitSource: {
        type: "github",
        repoId: String(repo.id),
        ref: "main",
        sha: commit,
      },
    },
  });

  const settled = await waitForDeployment(deployment.id, job, store);
  const state = String(settled.readyState || settled.state || "").toUpperCase();
  if (!["READY", "SUCCEEDED"].includes(state)) {
    throw new Error(`Vercel deployment ended in ${state || "an unknown state"}.`);
  }

  return {
    deployment: `https://${settled.url || deployment.url}`,
    vercelProject: "https://vercel.com/dashboard",
  };
}

export async function runCommand(command, args, options = {}) {
  const timeoutMs = options.timeoutMs || config.commandTimeoutMs;
  const captureLimit = options.captureLimit || 12000;
  return new Promise((resolvePromise, rejectPromise) => {
    const child = spawn(command, args, {
      cwd: options.cwd,
      env: options.env || process.env,
      shell: false,
      stdio: ["ignore", "pipe", "pipe"],
    });
    let output = "";
    const append = (chunk) => {
      output += chunk.toString();
      if (output.length > captureLimit) output = output.slice(-captureLimit);
    };
    child.stdout.on("data", append);
    child.stderr.on("data", append);
    const timer = setTimeout(() => child.kill("SIGKILL"), timeoutMs);
    child.on("error", (error) => {
      clearTimeout(timer);
      error.output = output;
      rejectPromise(error);
    });
    child.on("close", (code, signal) => {
      clearTimeout(timer);
      if (code === 0) return resolvePromise({ code, output });
      const error = new Error(`${command} ${args.join(" ")} failed (${signal || code}).`);
      error.output = output;
      rejectPromise(error);
    });
  });
}

async function chooseRepositoryName(prompt, id) {
  const base = sanitiseRepoName(prompt.split(/[.!?\n]/)[0].split(/\s+/).slice(0, 7).join("-")) || "generated-website";
  const candidates = [base, `${base}-${id.slice(0, 6)}`, `site-${id.slice(0, 8)}`];
  for (const candidate of candidates) {
    const response = await fetch(
      `https://api.github.com/repos/${encodeURIComponent(config.githubOwner)}/${encodeURIComponent(candidate)}`,
      { headers: githubHeaders() },
    );
    if (response.status === 404) return candidate;
  }
  return `site-${Date.now()}`;
}

async function waitForDeployment(id, job, store) {
  const deadline = Date.now() + config.commandTimeoutMs;
  let latest = null;
  while (Date.now() < deadline) {
    latest = await vercelRequest(`/v13/deployments/${id}`);
    const state = String(latest.readyState || latest.state || "").toUpperCase();
    store.log(job, "info", `Vercel deployment: ${state || "QUEUED"}`);
    if (["READY", "SUCCEEDED", "ERROR", "FAILED", "CANCELED", "CANCELLED"].includes(state)) return latest;
    await new Promise((resolvePromise) => setTimeout(resolvePromise, 5000));
  }
  throw new Error("Vercel deployment did not finish before the configured timeout.");
}

async function githubRequest(path, options = {}) {
  const response = await fetch(`https://api.github.com${path}`, {
    method: options.method || "GET",
    headers: githubHeaders(),
    ...(options.body ? { body: JSON.stringify(options.body) } : {}),
  });
  return parseApiResponse(response, "GitHub");
}

function githubHeaders() {
  return {
    Accept: "application/vnd.github+json",
    Authorization: `Bearer ${config.githubToken}`,
    "Content-Type": "application/json",
    "X-GitHub-Api-Version": "2022-11-28",
    "User-Agent": "site-forge",
  };
}

async function vercelRequest(path, options = {}) {
  const url = new URL(`https://api.vercel.com${path}`);
  if (config.vercelTeamId) url.searchParams.set("teamId", config.vercelTeamId);
  const response = await fetch(url, {
    method: options.method || "GET",
    headers: {
      Authorization: `Bearer ${config.vercelToken}`,
      "Content-Type": "application/json",
    },
    ...(options.body ? { body: JSON.stringify(options.body) } : {}),
  });
  return parseApiResponse(response, "Vercel");
}

async function parseApiResponse(response, service) {
  const text = await response.text();
  let payload = {};
  try {
    payload = text ? JSON.parse(text) : {};
  } catch {
    payload = { message: text };
  }
  if (!response.ok) {
    const message = payload?.error?.message || payload?.message || `${service} request failed with status ${response.status}.`;
    const error = new Error(message);
    error.status = response.status;
    error.payload = payload;
    throw error;
  }
  return payload;
}
